[project]
name = "fast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.3",
    "fastapi-utils>=0.8.0",
    "pydantic[email]>=2.12.0",
    "typing-inspect>=0.9.0",
    "uvicorn>=0.37.0",
]
